# Generated by Django 3.2 on 2021-05-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='签名'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app01.Tag'),
        ),
    ]
