# Generated by Django 3.2.1 on 2021-05-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='nid',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
