# Generated by Django 3.2.1 on 2021-05-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20210505_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='userinfo_test',
            name='age',
        ),
        migrations.AddField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo_test',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo_test',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo_test',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='签名'),
        ),
        migrations.AlterField(
            model_name='userinfo_test',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo_test',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
